version: '3.3'
services:
  esp32-dev:
    build: .
    volumes:
      - .:/workspace
      - /dev:/dev
    privileged: true
    working_dir: /workspace
    command: bash -c "source /opt/esp-idf/export.sh && bash"